name: Sync with S3
on:
  push:
    branches:
      - main # Change this to your main branch name if it's different

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install AWS CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y awscli

      - name: Sync with S3
        env:
          AWS_S3_BUCKET: ${{ secrets.gracit.click }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AKIA6GBME5OCTNLPLKPC }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.JtvGGPNpGgMlLGxJosRgQMXYs068C7TTxG8HAu09 }}
          AWS_DEFAULT_REGION: eu-west-2  # Replace with your AWS region
        run: |
          aws s3 sync . s3://gracit.click/
